FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    build-essential gcc g++ default-jdk \
    curl python3 python3-pip \
    golang-go \
    nodejs npm && \
    apt-get clean

WORKDIR /app

COPY executor.py .

COPY requirements.txt .

RUN pip3 install -r requirements.txt

ENTRYPOINT ["python3", "executor.py"]
