FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

# Install system dependencies
RUN apt-get update && \
    apt-get install -y \
    build-essential gcc g++ default-jdk \
    curl python3 python3-pip \
    golang-go \
    nodejs npm && \
    apt-get clean

WORKDIR /app

# Copy your files
COPY executor.py .
COPY host.py .
COPY requirements.txt .

# Install Python packages
RUN pip3 install -r requirements.txt

# Start Flask API
ENTRYPOINT ["python3", "executor.py"]
